Project3/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for reload_controller:

  # GET the empty form that allows the admin to specify what data gets reloaded into the database
  get 'reload/new', to: 'reload#new'

  # Use the form data to reload the database based on the specified parameters
  post 'reload', to: 'reload#reload_database'

  # 2nd reload method, this uses only term code to reload the database
  post 'reload2', to: 'reload#reload_database2'

  # auto-generated Devise routes.
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # CRUD routes for courses and their associated sections.
  resources :courses do
    resources :sections
  end

  # # CRUD routes for endorsing a grader
  resources :recommendations

  # CRUD routes for status requests: this refers to new instructors and admins that are awaiting approval from existing admins.
  resources :requests

  # CRUD routes for grader applications.
  resources :grader_applications do
    resources :availabilities
  end

  # CRUD routes for graders and their assigned sections.
  resources :grader_assignments
  # CRUD routes for viewing sections with enough graders.
  resources :assigned_sections, only: %i[index destroy]

  # Check if the user is signed in. If signed in, go to home page.
  # Else, go to sign in.
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # match all unexisting paths back to home page
  get '*path' => redirect('/')
end

Project3/app/controllers/grader_applications_controller.rb
# frozen_string_literal: true

# This controller handles all actions associated with student grader applications. It allows students to create and delete new applications and view
# all of their active applications,
# and admins to approve/reject applications and view all student applications.
class GraderApplicationsController < ApplicationController
  before_action :find_app,
                only: %i[show edit update destroy]
  before_action :authenticate
  before_action :find_qualified_sections, only: %i[show]
  before_action :check_admin, only: %i[update]
  before_action :check_student, only: %i[new create]

  # If admin, list the students that want to apply as a grader.
  # If student, list all of the applications belonging to student.
  def index
    if current_user.role == 'admin'
      @pagy_apps, @applications = pagy(Application.where('is_accepted = ?', false), page_param: :page_apps)
      @pagy_approved, @approved = pagy(Application.where('is_accepted = ?', true), page_param: :page_approved)
    elsif current_user.role == 'student'
      @pagy_apps, @applications = pagy(Application.where('user_id = ?', current_user.id), page_param: :page_apps)
    end
  end

  # HTML form that allows students to create a new application.
  def new
    @application = Application.new
  end

  # Creates a new grader application.
  def create
    # Create the new application using the app params.
    @application = Application.new(app_params)
    if @application.save
      # if app saved successfully, get its id to associate each new availability, course qual, and course pref with it
      id = @application.id
      # for each availability slot filled out, create a new row in Availabilities table associated with this application
      # if a row was left empty, don't add a row for it into availabilities
      params[:availabilities][:availabilities].each do |h|
        next unless h['start_time'].length.positive? || h['end_time'].length.positive?

        @availability = Availability.new(application_id: id, start_time: h['start_time'], end_time: h['end_time'],
                                         day_of_week: h['day_of_week'])
        @availability.save
      end
      # repeat for each course qualification slot
      params[:course_qualifications][:course_qualifications].each do |h|
        # if a row is left empty from the form, don't add a row for it into the database
        next unless h['course_num'].length.positive?

        # first, find the course id associated with this course
        c = Course.find_by number: h['course_num']
        # only add a row for this course qualification if the course number is a valid course present in the catalog
        if c
          @qual = CourseQualification.new(application_id: id, course_id: c.id)
          @qual.save
        end
      end
      # repeat for each course preference slot
      params[:course_preferences][:course_preferences].each do |h|
        # if a row is left empty from the form, don't add a row for it into the database
        next unless h['course_num'].length.positive?

        # find the course id associated with this course num
        c = Course.find_by number: h['course_num']
        # only add a row for this course preference if the course number is a valid course present in the catalog
        if c
          @pref = CoursePreference.new(application_id: id, course_id: c.id)
          @pref.save
        end
      end
      # display success message if app is saved, else display error message
      flash[:notice] = 'Application Successfully Created'
      redirect_to action: :index
    else
      flash[:notice] = 'Action Failed'
      render 'new'
    end
  end

  # Shows the contact info, availability, recommendations, and course preferences/qualifications of given student.
  def show
    # find any instructor recommendations that have been made for the student (for admin view only)
    @recs = Recommendation.where('student_email= ?', @application.user.email)
  end

  # Approves the application of given student.
  # Notifies if update was successful or not.
  def update
    @application = Application.find(params[:id])
    # Display an error message if the application can't be found.
    if @application.nil?
      flash.now[:notice] = 'Grader Application Not Found'
    # If the application was found, update their record in the database to mark them as approved.
    elsif @application.update(is_accepted: true)
      flash[:notice] = 'Grader Application Approved'
    # Display an error message if the approval failed when updating the database.
    else
      flash[:notice] = 'Failed to Approve Grader Application'
    end
    redirect_to action: :index
  end

  # Delete the application of given student if the student deletes it, or if the admin rejects it.
  # Notifies if deletion was successful or not.
  def destroy
    # find the user_section instances that are associated with this application's user
    # for each section associated with this user, find the one whose course falls under the deleted application's term
    @section = UserSection.where('user_id = ?', @application.user_id)
    if @section
      @section = @section.select { |us| us.section.course.term == @application.term }
      @section = @section.select { |us| us.first.section } if @section
    end

    if @application.destroy && @application.user.sections.delete(@section)
      flash[:notice] = if current_user.role == 'admin'
                       end
      'Grader Application Deleted'
    else
      flash[:error] = 'Failed to Remove Grader Application'
    end
    redirect_to action: :index
  end

  private

  # This function will match an application to all sections the student is available and qualified for,for the given term, based on the app's availability and qualified courses.
  def find_qualified_sections
    # This array will hold all the sections the app is qualified for
    @qual_sections = []
    # Find all courses with terms that match the application's term
    term_courses = Course.all.select { |c| c.term == @application.term }
    # Find all the term_courses whose course number matches a course number given in the app's course qualifications
    qual_courses = []
    term_courses.each do |course|
      @application.course_qualification.each do |cq|
        qual_courses << course if course.number == cq.course.number
      end
    end
    # now check each qualified course's section with the app's availabilities to see if the student is available for that section
    qual_courses.each do |course|
      course.sections.each do |sec|
        # only match availabilities if this section is in need of graders, else continue to next iteration
        next if sec.user_section.length == sec.num_graders_required

        # For each section of each course, first see if the section's days of the week match the days of week for which availabilities were filled out for
        # Strategy here: Collect an array of the section's days of the week and the available days of the week. If the arrays don't match, continue to next iteration of loop
        available_days = []
        section_days = []
        # if the section holds class on Monday, add it to section_days
        if sec.monday
          section_days << 'Monday'
          # if the section holds class on Monday and the application has availabilities listed on Monday, add it to available_days
          if @application.availabilities.select { |a| a.day_of_week == 'Monday' }.length.positive?
            available_days << 'Monday'
          end
        end
        # Repeat this logic for all other days of the school week
        if sec.tuesday
          section_days << 'Tuesday'
          if @application.availabilities.select { |a| a.day_of_week == 'Tuesday' }.length.positive?
            available_days << 'Tuesday'
          end
        end
        if sec.wednesday
          section_days << 'Wednesday'
          if @application.availabilities.select { |a| a.day_of_week == 'Wednesday' }.length.positive?
            available_days << 'Wednesday'
          end
        end
        if sec.thursday
          section_days << 'Thursday'
          if @application.availabilities.select { |a| a.day_of_week == 'Thursday' }.length.positive?
            available_days << 'Thursday'
          end
        end
        if sec.friday
          section_days << 'Friday'
          if @application.availabilities.select { |a| a.day_of_week == 'Friday' }.length.positive?
            available_days << 'Friday'
          end
        end
        # Check if the resulting available days array matches the days the section is offered. If not, continue to next iteration of loop
        next if section_days != available_days

        # Now for each day the section is offered, check the section's start and end time against all the available time slots for that day
        # If an open time slot is found for that day, add it to the list of matching days
        matching_days = []
        available_days.each do |day|
          @application.availabilities.select { |a| a.day_of_week == day }.each do |avail|
            # if the availability start time is earlier than/equal to  the section start time, AND the availability end time is later than/equal to the
            # section end time, we've found a matching time slot for that day; add it to the matching days array
            next unless ((avail.start_time <=> sec.start_time) <= 0) && ((avail.end_time <=> sec.end_time) >= 0)

            # If a matching time slot has already been found for the current day, skip
            matching_days << day unless matching_days.include?(day)
          end
        end
        # Finally, check if we have found matching time slots for ALL days the section is offered by checking if matching_days equals section_days
        # if the two arrays match, add the section to @qual_sections
        @qual_sections << sec if matching_days == section_days
      end
    end
  end

Project3/app/views/grader_applications/index.html.erb
<div class="ml-5">
<% if current_user.role == "admin" %>
    <h1>CSE Student Grader Applications</h1>
    <p>Welcome to the Grader Applications Dashboard!<br>
    Here, you can view pending student grader applications and approve or reject them. You can also view all approved applications.</p>
    <table id = "applicationTable" class = "table" >
        <tr>
        <td>
        <h4>Pending</h4>
        <table id = "pendingTable">
        <thead>
            <tr id = "headerRow" class = "text-center">
                <th>Student Name</th> <th>Term</th> <th>Campus</th> <th colspan = "3" >Actions</th>
            </tr>
        </thead>
        <tbody> 
            <% @applications.each do |application| %>
                <tr> 
                    <td><%= application.user.fname %> <%= application.user.lname %></td>
                    <td><%= application.term %></td>
                    <td><%= application.campus %></td>
                    <td><%= link_to 'Show', grader_application_path(application) %></td>
                    <td><%= button_to 'Approve', grader_application_path(application), method: :patch, class: 'btn btn-small btn-primary mx-2' %>
                    <td><%= button_to 'Reject', grader_application_path(application), method: :delete, class: 'btn btn-small btn-primary mx-2', data: {turbo_confirm: "Are you sure you want to reject this application?"} %>
                </tr>
            <% end %>
        </tbody>
        </table>
        </td>
        <td>
        <h4>Approved</h4>
        <table id = "approvedTable">
        <thead>
            <tr id = "headerRow" class = "text-center">
                <th>Student Name</th><th>Email</th> <th>Term</th> <th>Campus</th> <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @approved.each do |application| %>
                <tr> 
                    <td><%= application.user.fname %> <%= application.user.lname %></td>
                    <td><%= application.user.email %></td>
                    <td><%= application.term %></td>
                    <td><%= application.campus %></td>
                    <td><%= link_to 'Show', grader_application_path(application) %></td>
                    <td><%= button_to 'Delete', grader_application_path(application), method: :delete, class: 'btn btn-small btn-primary mx-2', data: {turbo_confirm: "Are you sure you want to delete this application?"} %>
                </tr>
                <%end%>
        </table>
        </td>
        </tr>
    </table>
<% elsif current_user.role == "student" %>
    <h2>CSE Student Grader Applications</h2>
    <% if @applications.length > 0 %>
        <p>
            You currently have application(s) on record to be a student grader. They are listed below.
            <br>You must submit a new application for each semester of courses.
            <br>Once an application has been approved, the status of your application will be updated.
            <br>You may view or delete each of your applications here. 
            <br>NOTE: You may only delete an application while it is still pending. If you'd wish to renege your offer after your application
            is approved, you must contact an administrator.<br>
        </p>
        <table id="applicationTable" class="table"> 
            <thead>
                <tr id="headerRow" class="text-center"> 
                    <th>Student Name</th> <th>Term</th> <th>Campus</th> <th colspan = "2">Actions</th> <th>Status</th> <th>Assigned Section</th>
                </tr>
            </thead>
            <tbody> 
                <% @applications.each do |application| %>
                    <tr> 
                        <td><%= application.user.fname %> <%= application.user.lname %></td>
                        <td><%= application.term %></td>
                        <td><%= application.campus %></td>
                        <td><%= link_to 'Show', grader_application_path(application) %></td>
                        <% if !application.is_accepted %>
                            <td><%= button_to 'Delete', grader_application_path(application), method: :delete, class: 'btn btn-small btn-primary mx-2', data: {turbo_confirm: "Are you sure you want to delete this application?"} %></td>
                        <% end %>
                        <td>
                            <% if application.is_accepted %>
                                <%= "Accepted" %>
                            <% else %>
                                <%= "Pending" %>
                            <% end %>
                        </td>
                        <td>
                            <%if application.is_accepted && application.user.user_section.length > 0%>
                                <% sec = application.user.user_section.select{|us| us.section.course.term == application.term }%>
                                <%="Course: "%>
                                <%= sec.first.section.course.number%>, 
                                <%=" Section: "%><%= sec.first.section.section_number%>
                             <%else%>
                                <%="N/A"%>
                             <%end%>   
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <% if @applications.length < 3%>
        <p>
            <br>Apply for another term:
        </p>
        <%= link_to "New Application", new_grader_application_path %>
        <%end%>
    <% else %>
        <p>
            You currently have no active applications on record for a CSE student grader position.
            <br>Start a new application:
        </p>
        <%= link_to "New Application", new_grader_application_path %>
    <% end %>
<% end %>
</div>

<%== pagy_bootstrap_nav(@pagy_apps) %>
<% if current_user.role == "admin"%>
<%== pagy_bootstrap_nav(@pagy_approved) %>
<%end%>

Project3/app/views/grader_applications/new.html.erb
<% if current_user.role == "student" %>
    <h1>New CSE Student Grader Application</h1>

    <br>
    <h4>Contact Information</h4>
    <p>
        <br>Student Name: <%= current_user.fname %> <%= current_user.lname %> 
        <br>Email: <%= current_user.email %>
        <br>
        <br>
        First, select the term and campus you are applying for (NOTE: you may only submit one application per term): 
    </p>

    <%= form_with model: @application, url: grader_applications_path, method: :post, local: true do |f| %>
        <% apps = Application.where("user_id = ?", current_user.id)
            used_terms = Array.new
            apps.each do |app|
            used_terms << app.term
        end %>
        <% a = ["Spring 2023", "Autumn 2023", "Summer 2023"] - used_terms %>
        <%= f.select :term, a %>
        <%= f.select :campus, ["Columbus", "Newark", "Mansfield", "Wooster", "Marion", "Lima"] %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :is_accepted, value: false %>
 
        <br>
        <br>
        <h3>Availability</h3>
        <p>
            Instructions: for each day of the week, fill in all the start and end times in which you are free. Click "Add row" to add as many time blocks as you need.<br>
            CONSTRAINTS: </p>
            <ul>
            <li>Only input availabilities between 8AM and 9PM.</li>
            <li>You must specify am or pm for each time slot.</li>
            <li>For single-digit times before 12:00pm, you must list the time as 0H:MMam. (ex. 09:00am, 08:00am)</li>
            <li>For times after 12:00pm, a leading 0 is unnecessary. Please list the time as H:MMpm (ex. 5:00pm, 6:30pm)</li>
            <li>Even if a time slot is on the hour (ex. 9am), you must list it in H:00 format. (ex. 09:00am, 5:00pm)</li>
            </ul>
        <p>
        If you do not meet the above requirements when filling out your availabilities, they will still be recorded in the system, but 
        our automatic section-matching feature will not work properly, at the inconvenience of the administrator assigning graders to sections.
        </p>
        <br>

        <%= fields_for :availabilities do |a| %>
            <% for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] %>
                <em><%= day %></em>
                <div id="rows<%= day %>">
                    <button type = 'button' id="addrowdays" onclick="addRowToDay('<%= day %>')">Add Row</button>
                    <div id="row<%= day %>">
                        <% currDay = day %>
                        <%= a.hidden_field "availabilities[][day_of_week]", value: currDay %>
                        <%= a.label "Start time" %><%= a.text_field "availabilities[][start_time]", class: "starttime" %>
                        <%= a.label "End Time" %><%= a.text_field "availabilities[][end_time]", class: "endtime" %>
                    </div>
                </div>
            <% end %>
        <% end %>

        <%= fields_for :course_qualifications, @course_qualification do |q| %>
            <br>
            <h3>Course Qualifications</h3>
            <p>Instructions: Please type in the COURSE NUMBER of all CSE courses you have taken at OSU. Click "Add Row" to add as many entries as you need.</p>
            <div id="rowsQual">
                <button type = 'button' id="addrowquals" onclick="addRowToQual()">Add Row</button>
                <div id="rowQual">
                    <%= q.label "Course Number"%><%=q.text_field "course_qualifications[][course_num]" %>
                </div>
            </div>
        <% end %>

        <%= fields_for :course_preferences, @course_preference do |p| %>
            <br>
            <h3>Course Preferences</h3>
            <p>Instructions: Please type in the COURSE NUMBER of any CSE courses you would prefer to grade. This must
            be a subset of your Course Qualifications. Click "Add Row" to add as many entries as you need.</p>
            <div id="rowsPref">
                <button type = 'button' id="addrowprefs" onclick="addRowToPref()">Add Row</button>
                <div id="rowPref">
                    <%=p.label "Course Number"%><%=p.text_field "course_preferences[][course_num]"%>
                </div>
            </div>
        <% end %>
        <%= f.submit "Submit" %>
    <% end %>
    <%= link_to "Back to Grader Applications", action: :index %>
<% end %>

<script>
function addRowToDay(day) {
    // create a new input field for start and end time
    let row=document.getElementById("row"+day);
    let newRow = row.cloneNode(true);
    document.getElementById("rows"+day).appendChild(newRow);
}

function addRowToQual() {
    let row=document.getElementById("rowQual");
    let newRow = row.cloneNode(true);
    document.getElementById("rowsQual").appendChild(newRow);
}

function addRowToPref() {
    let row=document.getElementById("rowPref");
    let newRow = row.cloneNode(true);
    document.getElementById("rowsPref").appendChild(newRow);
}
</script>

Project3/app/views/grader_applications/show.html.erb
<div class="ml-5">
<% if current_user.role == "admin" || current_user.role == "student" %>
    <h1>Grader Information</h1>

    <h4>First Name</h4>
    <p><%= @application.user.fname %></p>

    <h4>Last Name</h4>
    <p><%= @application.user.lname %></p>

    <h4>Email</h4>
    <p><%= @application.user.email %></p>

    <h4>Campus</h4>
    <p><%= @application.campus %></p>

    <h4>Term</h4>
    <p><%= @application.term %></p>

    <h3>Availability</h3>
    <% for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"] %>
        <h4><strong><%= day %></strong></h4>
        <table>
            <thead>
                <th>Start Time</th>  <th>End Time</th>
            </thead>
            <tbody>
                <% @application.availabilities.select{ |entry| entry.day_of_week==day }.each do |a| %>
                    <tr>
                        <td><%= a.start_time %></td>
                        <td><%= a.end_time %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    <% end %>
<% if current_user.role == "admin" %>
    <br><br><h4>Instructor Recommendations</h4>
    <table id = "recsTable" class = "table"> 
        <thead>
            <tr id = "headerRow" class = "text-center">
                <th>Instructor Email</th>
                <th>Instructor Name</th>
                <th>Recommended Course <em>(If Applicable)</em></th>
                <th>Recommended Section <em>(If Applicable)</em></th>
                <th>Recommendation Message</th>
                    
            </tr>
        </thead>
        <tbody>
         <%@recs.each do |r| %>
        <tr>
        <td><%=r.instructor_email%></td>
        <td><%=r.user.fname%> <%=r.user.lname%></td>
        <td><%= r.course_name %></td>
        <td><%= r.section_num%></td>
        <td><%= r.message %></td>
        </tr>
         <%end%>
        </tbody>
        </table>
          <% end %>


    <br><br><h4>Courses</h4>
    <table id = "courseTable" class = "table"> 
        <thread>
            <tr id = "headerRow" class = "text-center">
                <th>Course Qualifications</th>
                <th>Course Preferences</th>
    
                    <th>Qualified Sections in Need of Graders</th>

            </tr>
        </thread>
        <tbody>
            <tr>
                <td>
                    <% @application.course_qualification.each do |cq| %>
                        <p><%= cq.course.number %></p>
                    <% end %>
                </td>
                <td>
                    <% @application.course_preference.each do |cp| %>
                        <p><%= cp.course.number %></p>
                    <% end %>
                </td>
                
                    <td>
                        <% @qual_sections.each do |sec| %>
                            <p><%= sec.course.number %> - Section <%= sec.section_number %></p>
    
                        <% end %>
                    </td>
  
            </tr>
        </tbody>
    </table>
    <br>
    <% if current_user.role == "admin" && not(@application.is_accepted?) %>
        <td><%= button_to 'Approve Application', grader_application_path(@application), method: :patch %>
    <% end %>
    <br><%= link_to "Back to Grader Applications", action: :index %>
<% end %>
</div>