Project3/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for reload_controller:

  # GET the empty form that allows the admin to specify what data gets reloaded into the database
  get 'reload/new', to: 'reload#new'

  # Use the form data to reload the database based on the specified parameters
  post 'reload', to: 'reload#reload_database'

  # 2nd reload method, this uses only term code to reload the database
  post 'reload2', to: 'reload#reload_database2'

  # auto-generated Devise routes.
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # CRUD routes for courses and their associated sections.
  resources :courses do
    resources :sections
  end

  # # CRUD routes for endorsing a grader
  resources :recommendations

  # CRUD routes for status requests: this refers to new instructors and admins that are awaiting approval from existing admins.
  resources :requests

  # CRUD routes for grader applications.
  resources :grader_applications do
    resources :availabilities
  end

  # CRUD routes for graders and their assigned sections.
  resources :grader_assignments
  # CRUD routes for viewing sections with enough graders.
  resources :assigned_sections, only: %i[index destroy]

  # Check if the user is signed in. If signed in, go to home page.
  # Else, go to sign in.
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # match all unexisting paths back to home page
  get '*path' => redirect('/')
end

Project3/app/controllers/grader_assignments_controller.rb
# frozen_string_literal: true

# This controller handles all actions related to admins assigning grader applications to sections. It renders an "index" view that shows all
# course sections for the specified term that still need graders assigned, along with all grader applications that haven't been assigned to a
# section yet. From this page, the admin is able to assign graders to sections.
# This controller also supports a "create" method that creates a new row in sections_users when a grader is assigned to an application.
class GraderAssignmentsController < ApplicationController
  before_action :authenticate
  def index
    # get only the courses under the specified term
    # get only those applications that have been approved and for the current term
    term = ''
    if params[:term]
      term = params[:term]
      @courses = Course.where('term=?', term)
    else
      # if term isn't specified (i.e. on first visit to page), default to spring 2023 term
      term = 'Spring 2023'
      @courses = Course.where('term = ?', term)
    end
    accepted_apps = Application.where('term = ? AND is_accepted = ?', term, true)

    # now get the applications that have not been assigned to a section yet (i.e. the associated user isn't in user_section table)
    @applications = []
    # only add an accepted app to @applications if its associated user id is not already in user_section for the given term
    accepted_apps.each do |a|
      @applications << a if a.user.user_section.select { |us| us.section.course.term == term }.empty?
    end

    # build an array of sections from each course that still need a grader
    @grader_sections = []
    @courses.each do |c|
      c.sections.each do |s|
        # if this section appears in the user_sections table less than the amount of graders required (meaning less graders
        # have been assigned than are needed), add this section to @grader_sections
        @grader_sections << s if s.user_section.length < s.num_graders_required
      end
    end
    @pagy_apps, @applications = pagy_array(@applications, page_param: :page_apps)
    @pagy_graders, @grader_sections = pagy_array(@grader_sections, page_param: :page_graders)
  end

  # When an admin assigns a grader to a section, this method will create a new row in sections_users associating the section and grader.
  def create
    # find the user id associated with the email passed in from params
    @user = User.find_by(email: params[:email])
    @user_section = UserSection.new(user_id: @user.id, section_id: params[:section_id])
    flash[:notice] = if @user_section.save
                       'Grader Successfully Assigned To Section'
                     else
                       'Error Assigning Grader To Section. Please try again.'
                     end
    redirect_to action: :index
  end

  def destroy; end

  private

  # if a non-admin or someone who isnt signed in tries to navigate to any URL associated with this controller, redirect them back to home page
  def authenticate
    redirect_to '/' unless current_user&.role == 'admin'
  end
end

Project3/app/views/grader_assignments/index.html.erb
<% if current_user.role == "admin" %>
    <h1 class="ml-5 mr-5">CSE Student Grader Assignment Dashboard</h1>
    <p class="ml-5 mr-5">Welcome to the Grader Assignment Dashboard!<br>On this page, you can view sections that have not yet had enough graders assigned to them,
    view approved grader applications that have not yet been assigned to a section, and match qualified graders to sections.<br>You can also click the link below to
    view all the course sections that have the required amount of graders assigned.<br>
    

    <br><b><%= link_to "See Sections With All Necessary Graders Assigned", assigned_sections_path %></b><br>
    <br><b>Instructions:</b><br></p>
    <ul class="ml-5 mr-5">
    <li>Select the term you would like to view applications and sections for (on first load, defaults to Spring 2023)</li>
    <li>On the left, all sections for the specified term that still need graders assigned will be listed.</li>
    <li>On the right, all approved grader applications for the specified term will be listed, along with the course sections they qualify for based on 
    their course qualifications and availabilities. Click "Show" to view more information about this grader application, including their full availability and list
    of course preferences/qualifications.</li>
    <li>When you would like to assign a grader to a section, simply choose that grader's email from the drop-down menu next to that section and click "Assign" to update the system (The drop-down will only appear if there are unassigned applications available).</li>

    <br><h5>Choose Term:</h5>
    <%= bootstrap_form_tag url: grader_assignments_path, method: :get do |f| %>
        <%= f.select :term, options_for_select(["Spring 2023", "Summer 2023", "Autumn 2023"], selected: params[:term]), {}%>  <%= f.submit "Apply Term" %>
    <% end %>

    <br><table id = "dashboardTable" class = "table">
    <tr>
    <td>
    <h4>Sections In Need Of Graders</h4>
    <table id = "sectionsTable">
        <thead>
            <tr id = "headerRow" class = "text-center">
                <th>Course Number</th><th>Campus</th> <th>Section Number</th><th>Start Time</th><th>End Time</th><th>Days of Week</th> <th>Num. Graders Required</th> <th>Graders Assigned</th>
            </tr>
        </thead>
        <tbody>
        <% @grader_sections.each do |grader_section| %>
        <% app_emails = Array.new 
                         @applications.each do |a|
                        app_emails << a.user.email
                        end %>
                <tr>
                    <td><%= grader_section.course.number %></td>
                    <td><%= grader_section.course.campus %></td>
                    <td><%= grader_section.section_number %></td>
                    <td><%= grader_section.start_time %></td>
                    <td><%= grader_section.end_time %></td>
                    <!-- Create a string depicting the section's days of the week -->
                    <% days = ""%>
                    <% if grader_section.monday %>
                        <% days += "M"%>
                    <% end%>
                    <% if grader_section.tuesday %>
                        <% days += " Tu"%>
                    <% end%>
                    <% if grader_section.wednesday %>
                        <% days += " W"%>
                    <% end%>
                    <% if grader_section.thursday %>
                        <% days += " Th"%>
                    <% end%>
                    <% if grader_section.friday %>
                        <% days += " F"%>
                    <% end%>
                    <% if grader_section.saturday %>
                        <% days += " Sat"%>
                    <% end%>
                    <% if grader_section.sunday %>
                        <% days += " Sun"%>
                    <% end%>

                    <td><%= days %></td>
                    <td><%= grader_section.num_graders_required %></td>
                    <td>
                        <% if grader_section.user_section.length == 0 %>
                            <%= "No Assigned Graders" %>
                        <% else %>
                            <% grader_section.user_section.each do |us| %>
                                <%= us.user.email %>
                        
                            <% end %>
                        <% end %>
                        <% if app_emails.length > 0%>
                        <%= bootstrap_form_tag url: grader_assignments_path, method: :post do |f| %>
                          <%= f.select :email, app_emails, label: "Assign Grader: " %>  
                          <%= f.hidden_field :section_id, value: grader_section.id%>
                          <%= f.submit "Assign" %>
                         <% end %>
                         <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
        </table>
        </td>
        <td>
        <h4>Approved Applications</h4>
       <table id = "applicationsTable">
       <thead>
            <tr id = "headerRow" class = "text-center">
                <th>Student Name</th><th>Email</th> <th>Term</th> <th>Campus</th><th colspan = "3" >Actions</th>
            </tr>
        </thead>
        <tbody> 
            <% @applications.each do |application| %>
                <tr> 
                    <td><%= application.user.fname %> <%= application.user.lname %></td>
                    <td><%= application.user.email %></td>
                    <td><%= application.term %></td>
                    <td><%= application.campus %></td>
                    <td><%= link_to 'Show', grader_application_path(application) %></td>
                </tr>
                <%end%>
    </table>
    </td>
    </tr>
    </table>
<% end %>

<%== pagy_bootstrap_nav(@pagy_apps) %>
<%== pagy_bootstrap_nav(@pagy_graders) %>