Project3/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Routes for reload_controller:

  # GET the empty form that allows the admin to specify what data gets reloaded into the database
  get 'reload/new', to: 'reload#new'

  # Use the form data to reload the database based on the specified parameters
  post 'reload', to: 'reload#reload_database'

  # 2nd reload method, this uses only term code to reload the database
  post 'reload2', to: 'reload#reload_database2'

  # auto-generated Devise routes.
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # CRUD routes for courses and their associated sections.
  resources :courses do
    resources :sections
  end

  # # CRUD routes for endorsing a grader
  resources :recommendations

  # CRUD routes for status requests: this refers to new instructors and admins that are awaiting approval from existing admins.
  resources :requests

  # CRUD routes for grader applications.
  resources :grader_applications do
    resources :availabilities
  end

  # CRUD routes for graders and their assigned sections.
  resources :grader_assignments
  # CRUD routes for viewing sections with enough graders.
  resources :assigned_sections, only: %i[index destroy]

  # Check if the user is signed in. If signed in, go to home page.
  # Else, go to sign in.
  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # match all unexisting paths back to home page
  get '*path' => redirect('/')
end

Project3/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-end p-3" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if current_user %>
        <li class="nav-item"> <%= link_to "Home", authenticated_root_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

Project3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSU CSE Courses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <h1 class="mt-4 text-center"><b>OSU CSE Course Catalog</b></h1>
   <%= render "layouts/navbar" %>

   <% if flash.any? %>
     <div id="banner">
     <%flash.each do |key, message|%>
       <div class = "flash <%= key %>" >
         <%=message%>
       </div>
     <%end%>
     </div>
   <%end%>
<!-- BUTTONS FOR ADMINS -->
   <% if current_user.role == "admin"%>
     <table id = "menuBar">
        <tr>
    
            <td>
                <%= button_to "Browse Catalog", courses_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
            </td>
            <% if current_user.pending_approval? %>
            
        <p>You are currently pending admin approval. Until you are approved, you are only able to browse the course catalog.</p>

                <td>
                    <%= button_to "Status Requests", requests_path, method: :get, class: "btn btn-small btn-primary mx-2", :disabled => true%>
                </td>
                <td>
                  <%= button_to "Grader Applications", grader_applications_path, method: :get, class: "btn btn-small btn-primary mx-2", :disabled => true %>
                </td>
                <td>
                  <%= button_to "Grader Assignments", grader_assignments_path, method: :get, class: "btn btn-small btn-primary mx-2", :disabled => true %>
                </td>
                <td>
                    <%= button_to "Reload Database", "/reload/new", method: :get, class: "btn btn-small btn-primary mx-2", :disabled => true %>
                </td>
            <% else %>
                <td>
                    <%= button_to "Status Requests", requests_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
                </td>
                <td>
                  <%= button_to "Grader Applications", grader_applications_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
                </td>
                <td>
                  <%= button_to "Section Grader Assignments", grader_assignments_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
                </td>
                <td>
                    <%= button_to "Reload Database", "/reload/new", method: :get, class: "btn btn-small btn-primary mx-2" %>
                </td>
            <% end %>
    
        </tr>
    </table>
    <hr>
<!-- BUTTONS FOR INSTRUCTORS -->
    <%elsif current_user.role == "instructor" %>
     
    <table id = "menuBar">
      <tr>
        <td>
          <%= button_to "Browse Catalog", courses_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
        </td>
        <% if current_user.pending_approval? %>
      <p>You are currently pending approval. Until you are approved by an admin, you are only able to browse the course catalog.</p>
      <td>
          <%= button_to "Submit a Grader Recommendation", new_recommendation_path, method: :get, class: "btn btn-small btn-primary mx-2", :disabled => true %>
        </td>
    <% else %>
        <td>
          <%= button_to "Submit a Grader Recommendation", new_recommendation_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
        </td>
        <%end%>
      </tr>
    </table>
    <hr>
<!-- BUTTONS FOR STUDENTS -->
    <%else%>
      <table id = "menuBar">
        <tr>
          <td>
            <%= button_to "Browse Catalog", courses_path, method: :get, class: "btn btn-small btn-primary mx-2" %>
          </td>
          <td>
            <%= button_to "Student Grader Applications", "/grader_applications", method: :get, class: "btn btn-small btn-primary mx-2" %>
          </td>
        </tr>
      </table>
    <hr>
    <%end%>
    <%= yield %>
  </body>
</html>

Project3/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>The Ohio State University Courses</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <div id = "header" class="mt-4 text-center">
            <h1>The Ohio State University Courses</h1>
        </div>
        <div class="ml-5 mt-5 text-center">
            <%= yield %>
        </div>
    </div>
</body>
</html>